name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up BuildKit Docker container builder to be able to build
    # multi-platform images and export cache
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      
    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker buildx build . \
          --file Dockerfile \
          --build-arg BASE_RUST_IMAGE_TAG=${{ vars.BASE_RUST_IMAGE_TAG }}
          --tag ${{ vars.IMAGE_PREFIX }}rust:${{ vars.IMAGE_TAG }}
          --platform linux/amd64,linux/arm64
          --push
